language: r

sudo: required

# Be strict when checking our package
warnings_are_errors: true

r_packages:
- testthat
- matrixStats
- knitr
- markdown
- png

bioc_packages:
- GenomicRanges
- genefilter

r_github_packages:
- jokergoo/circlize
- jokergoo/ComplexHeatmap
- jimhester/covr

bioc_required: true

r_check_args: --no-build-vignettes --no-vignettes

after_success:
  - Rscript -e 'library(covr);codecov()'
  
